name: golf_digital_pro
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^1.7.2
  google_maps_flutter: ^0.5.21+15
  json_serializable: ^3.2.5
  rxdart: ^0.22.6


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/golf.png
    - assets/map.png
    - assets/list.png

    - assets/courses.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SnowHut
      fonts:
        - asset: assets/fonts/SnowHut.ttf

    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf

    - family: TurretRoad
      fonts:
        - asset: assets/fonts/TurretRoad-Bold.ttf
        - asset: assets/fonts/TurretRoad-ExtraBold.ttf
        - asset: assets/fonts/TurretRoad-ExtraLight.ttf
        - asset: assets/fonts/TurretRoad-Light.ttf
        - asset: assets/fonts/TurretRoad-Regular.ttf
        - asset: assets/fonts/TurretRoad-Medium.ttf



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
